baseURL = "https://tatimun.github.io/tatisnote/"
languageCode = "es"
title = "Apuntatis"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

# ðŸ‘‡ Estas dos opciones deben ir al nivel raÃ­z (no dentro de [params])
relativeURLs = true
canonifyURLs = false

[params]
author = "Tati"
description = "Rompiendo cosas ðŸ˜‹"
github = "tatimun"
twitter = "titamun"
linkedin = "tatianasmunoz"
email = "apuntatis@gmail.com"
url = "https://tatimun.github.io/tatisnote/"
keywords = "blog, google analytics"
rss = true
lastmod = true
userStatusEmoji = "ðŸ˜€"
favicon    = "images/github-mark.png"
avatar     = "images/avatar.gif"
headerIcon = "images/github-mark-white.png"

location = "Argentina"
enableGitalk = true
enableSearch = true

[params.gitalk]
clientID = "Ov23liygGvPBcLz4XICU"
clientSecret = ""   # en prod, usÃ¡ uno real o desactivÃ¡ Gitalk
repo = "tatisnote"
owner = "tatimun"
admin = "tatimun"
id = "location.pathname"
labels = "gitalk"
perPage = 15
pagerDirection = "last"
createIssueManually = true
distractionFreeMode = false

[[params.links]]
title = "Link"
href = "https://github.com/tatimun"

[[params.links]]
title = "Link2"
href = "https://tatimun.github.io/tatisnote/"
icon = "images/avatar.gif"   # antes tenÃ­as un punto extra en 'tatisnote.'
 
[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[services.googleAnalytics]
ID = "UA-123456-799"

[outputs]
home = ["html", "json"]

[outputFormats.json]
mediaType = "application/json"
baseName = "index"
isPlainText = false
