baseURL = "https://tatimun.github.io/tatisnote/"
languageCode = "en-es"
title = "Apuntatis"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Tati"
  description = "Rompiendo cosas ğŸ˜‹"
  github = "tatimun"
  twitter = "titamun"
  linkedin = "tatianasmunoz"
  email = "apuntatis@gmail.com"
  url = "https://tatimun.github.io/apuntatis"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "ğŸ˜€"
  favicon = "/images/github.png"
  avatar = "/images/IlustracioÌn_sin_tiÌtulo.gif"
  headerIcon = "/images/github-mark-white.png"
  location = "Argentina"
  enableGitalk = true
  enableSearch = true


  [params.gitalk]
    clientID = "Ov23liygGvPBcLz4XICU"
    clientSecret = "b0214c0ab7a754c256ec21fd8b211201ccc9658d"
    repo = "tatisnote"
    owner = "tatimun"
    admin = "tatimun"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  [[params.links]]
    title = "Link"
    href = "https://github.com/tatimun"

  [[params.links]]
    title = "Link2"
    href = "https://tatimun.github.io/tatisnote/"
    icon = "https://tatimun.github.io/tatisnote/images/avatar.gif"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services.googleAnalytics]
  ID = "UA-123456-799"

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false